### DISCUSSION TITLE
Getting a "TFLint is not compatible with this version of the "aws" plugin" error

### DISCUSSION THREAD

**Discussion by knobotz** [terraform-linters/tflint#1606] [Q&A]
Hello,

I have the following action file:

```yaml
name: Lint
on:
  push:
    branches: [ main ]
  pull_request:

jobs:
  tflint:
    runs-on: ${{ matrix.os }}

    strategy:
      matrix:
        os: [ubuntu-latest]

    steps:
    - uses: actions/checkout@v3
      name: Checkout source code

    - uses: actions/cache@v3
      name: Cache plugin dir
      with:
        path: ~/.tflint.d/plugins
        key: ${{ matrix.os }}-tflint-${{ hashFiles('.tflint.hcl') }}

    - uses: terraform-linters/setup-tflint@v3
      name: Setup TFLint
      with:
        tflint_version: latest

    - name: Show version
      run: tflint --version

    - name: Init TFLint
      run: tflint --init

    - name: Run TFLint
      run: tflint -f compact
```

Unfortunately it currently fails with:
```
Run tflint -f compact
  tflint -f compact
  shell: /usr/bin/bash -e {0}
Failed to initialize plugins; TFLint is not compatible with this version of the "aws" plugin. A newer TFLint or plugin version may be required. Plugin version: 10, Client versions: [11]
Error: Process completed with exit code 1.
```

Any ideas? I'm not sure where to go from here, since I'm not using an aws plugin directly.
