### DISCUSSION TITLE
Annotations does not show up in PR

### DISCUSSION THREAD

**Discussion by ehsan310** [terraform-linters/tflint#1840] [Q&A]
Hey,

I have an github action and according to documentation `tflint -f compact` should create annotation in PR and be picked up by Matcher but the warnings and errors just got printed in action itself.

Any idea why this could happen ?
```

name: PR check

on:
  pull_request:
    branches:
      - master

jobs:
  tf-lint:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3
        name: Checkout source code

      - name: Setup TFLint
        uses: terraform-linters/setup-tflint@v3
        with:
          github_token: ${{ secrets.SA_GITHUB_REPO_TOKEN }}
          tflint_wrapper: false

      - name: Run TFLint
        run: tflint -f compact
        
      # - run: echo ${{ steps.tflint.outputs.stdout }}
      # - run: echo ${{ steps.tflint.outputs.stderr }}
      # - run: echo ${{ steps.tflint.outputs.exitcode }}
```

**Comment by MrBayene** [comment]
I have the same problem, the documentation says its should match the existing matchers but it only gets print in the action output.

**Comment by wata727** [comment]
Do you have an example of the output?
The matcher is regexp based and some messages may not match the regexp.
https://github.com/terraform-linters/setup-tflint/blob/v3.1.1/.github/matchers.json#L7

**Comment by Mi3-14159** [comment]
Hi i seem to have the same Problem.

That's is my github workflow:

```yaml
on:
  workflow_call:
    tflint-version:
      description: "TFLint version used for static checks"
      default: "latest"
      required: false
      type: string
    working-directory:
      required: true
      type: string
      description: The working directory to run terraform commands in

jobs:
  tflint:
    runs-on: ubuntu-latest
    permissions:
      contents: read
      checks: write
    steps:
      - uses: actions/checkout@v4

      - uses: terraform-linters/setup-tflint@v4
        with:
          tflint_version: ${{ inputs.tflint-version }}

      - run: tflint --init
        working-directory: ${{ inputs.working-directory }}

      - run: tflint --version
        working-directory: ${{ inputs.working-directory }}

      - name: TFLint
        run: tflint --chdir "${{ inputs.working-directory }}" --format compact ${{ inputs.tflint-args }}
```

And this is the tflint output:

```
Run tflint --chdir "oembed-adapter/terraform" --format compact 
  
1 issue(s) found:

Warning: oembed-adapter/terraform/versions.tf:3:11: Warning - Missing version constraint for provider "aws" in `required_providers` (terraform_required_providers)
Error: Process completed with exit code 2.
```

Do you see the problem?
