### ISSUE TITLE
Question: terraform_standard_module_structure for tfvars in a specific directory

### ISSUE THREAD

**Issue by bondezbond** [terraform-linters/tflint#1083]
I'm trying to follow best practices here and looking for guidance. I couldn't figure out the best practice on how to manage *.tfvars. My current practice is putting tfvars file in a directory names `inputs/` but this rule doesn't like that. Is there a way we can make it ignore a directory name?

```
.
├── README.md
├── data.tf
├── inputs
│   ├── dev.tfvars
│   ├── prod.tfvars
│   └── stage.tfvars
├── main.tf
├── outputs.tf
├── variables.tf
└── versions.tf
```

**Comment by bendrucker** [comment]
Can you share the error? That's unintentional, tfvars files (whether by environment or otherwise) are left up to the user and the goal of that rule is just to apply the recommendations in Terraform's own docs.

**Comment by bondezbond** [comment]
sure. I'm using this with pre-commit. So when I have my structure like mentioned above I get the following errors
pre-commit. Here's that file as well

.pre-commit.yaml
```
repos:
  - repo: git://github.com/antonbabenko/pre-commit-terraform
    rev: v1.48.0
    hooks:
      - id: terraform_fmt
      - id: terraform_validate
      - id: terraform_docs
      - id: terraform_tflint
        args:
          - '--args=--only=terraform_deprecated_interpolation'
          - '--args=--only=terraform_deprecated_index'
          - '--args=--only=terraform_unused_declarations'
          - '--args=--only=terraform_comment_syntax'
          - '--args=--only=terraform_documented_outputs'
          - '--args=--only=terraform_documented_variables'
          - '--args=--only=terraform_typed_variables'
          - '--args=--only=terraform_module_pinned_source'
          - '--args=--only=terraform_naming_convention'
          - '--args=--only=terraform_required_version'
          - '--args=--only=terraform_required_providers'
          - '--args=--only=terraform_standard_module_structure'
          - '--args=--only=terraform_workspace_remote'
  - repo: git://github.com/pre-commit/pre-commit-hooks
    rev: v3.4.0
    hooks:
      - id: check-merge-conflict
```


Run
```
$ pre-commit run -a terraform_tflint
Terraform validate with tflint...........................................Failed
- hook id: terraform_tflint
- exit code: 3

4 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_required_version.md

Warning: Module should include a main.tf file as the primary entrypoint (terraform_standard_module_structure)

  on main.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty variables.tf file (terraform_standard_module_structure)

  on variables.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

4 issue(s) found:

Warning: terraform "required_version" attribute is required (terraform_required_version)

  on  line 0:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_required_version.md

Warning: Module should include a main.tf file as the primary entrypoint (terraform_standard_module_structure)

  on main.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty outputs.tf file (terraform_standard_module_structure)

  on outputs.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md

Warning: Module should include an empty variables.tf file (terraform_standard_module_structure)

  on variables.tf line 1:
   (source code not available)

Reference: https://github.com/terraform-linters/tflint/blob/v0.23.1/docs/rules/terraform_standard_module_structure.md
```

when i remove my inputs directory everythings passes
