### ISSUE TITLE
JUnit Azure DevOps Test's

### ISSUE THREAD

**Issue by ASHR4** [terraform-linters/tflint#1406]
Using Azure DevOps to publish test results in the format of JUNIT using this command to generate output:

```hcl
$Output = docker run --rm -v "$($INPUT_WORK_DIR):/src" `
                    --entrypoint=/bin/sh ghcr.io/terraform-linters/tflint-bundle `
                    -c "tflint -v; tflint --init --config '/src/$INPUT_TFLINT_CONFIG'; tflint --config '/src/$INPUT_TFLINT_CONFIG' '/src/$tf_directory' --format='junit'" | Out-String
            $Output | Out-File -FilePath "$($INPUT_WORK_DIR)/TFLint/TFLint_$guid.xml"
```

I then Publish this task using:

```
- task: PublishTestResults@2
            condition: always()
            inputs:
              testRunTitle: "TFLint Analysis Results"
              failTaskOnFailedTests: false
              publishRunAttachments: true
              mergeTestResults: true
              testResultsFormat: "JUnit"
              testResultsFiles: |
                **/*.xml
              searchFolder: "$(System.DefaultWorkingDirectory)/TFLint"
            displayName: "Publish TFLint Results"
```

All of the above works and publishes the tests with no issues.

The issue comes from the XML it generates where the **classname** is the path in which has been scanned - **the issue with this** is that the Publish Test Task uses [this](https://docs.microsoft.com/en-us/azure/devops/pipelines/tasks/test/publish-test-results?view=azure-devops&tabs=junit%2Cyaml):

<img width="449" alt="image" src="https://user-images.githubusercontent.com/72310905/171216755-09913f46-06bb-42ca-b7c2-9e3b78012eee.png">

This causes the test title to be the error message and not the file path or a combination - **I suppose I would like an amended 
failure message to include the path it has scanned**:

```console
line 54, col 1, FIle [Path] Notice - `data_vnet` variable has no description (terraform_documented_variables)
```

<img width="308" alt="image" src="https://user-images.githubusercontent.com/72310905/171217585-4cfb5cb5-e42d-42ff-a788-cdb599632281.png">

I know I'm a small use case for this, I was hoping if anyone would have any advice or if this can be updated?
