### ISSUE TITLE
Feature request: Docker image to run against multiple directories

### ISSUE THREAD

**Issue by wyardley** [terraform-linters/tflint#926]
Since `tflint` doesn't support a recursive mode, for use in CI, it would useful if there were a variant of the Docker container that contains some way to check multiple files (e.g., a shell, such that something like `find . -type f -name "*.tf" -exec dirname {} \; | uniq | xargs -n1  tflint` can be run). I can see why it might not be ideal to build that into the default Dockefile, but some other lint tools (e.g., shellcheck) provide both options to support situations like this.

Or even an alternate entrypoint that supports checking a recusive filesystem hierarchy natively.

**Comment by bendrucker** [comment]
> but some other lint tools (e.g., shellcheck) provide both options to support situations like this

If you have specific examples you can link to that I would be helpful. There's discussion in https://github.com/terraform-linters/tflint/pull/841—I'm generally skeptical that TFLint should be solving this. Even more so of maintaining it in shell/a Dockerfile.

**Comment by wyardley** [comment]
https://hub.docker.com/r/koalaman/shellcheck-alpine comes to mind
https://github.com/koalaman/shellcheck#installing has a bit more context about how it's used.

I guess the question is, if I have a whole bunch of different states / directories to check, how would I handle that in CircleCI with the current Docker image, aside from creating a single workflow per directory / state?

Currently, we just bootstrap in a generic Terraform image by downloading the zip; had briefly moved to using the Docker image until I realized today that it doesn't actually operate recursively, the way most linters do.

A feature to accept multiple directories as arguments or to auto-discover directories would also resolve this issue, so if that WIP is going to go somewhere, that would definitely resolve the issue from my standpoint.

**Comment by bendrucker** [comment]
> I guess the question is, if I have a whole bunch of different states / directories to check, how would I handle that in CircleCI with the current Docker image, aside from creating a single workflow per directory / state?

Use the Docker image and just run your own custom command inside.

In your shellcheck example I don't see any recursive processing, I just see shell globbing:

```sh
shellcheck myscripts/*.sh
```

Terraform is not comparable though, because files don't matter, directories do.

I don't #841 landing either b/c you need to run `terraform init` before invoking `tflint --module`. Which speaks to the idea that module finding should be handled by a separate application/script rather than in an individual analysis tool.

For now the best answer is BYO shell script but if there were a solid binary application that could handle this we could certainly recommend it as well as build it into the Dockerfile. I've considered working on one but have never gotten around to it.

**Comment by wyardley** [comment]
> Use the Docker image and just run your own custom command inside.

Got it. I didn't see that the entrypoint could be overridden. Assuming the busybox utilities work Ok for my purposes, that should be good enough.

For installing plugins, is the recommendation to use wget directly?

**Comment by bendrucker** [comment]
Yep, I believe something like Circle is always going to try to invoke a shell wrapper around anything with `run`. For plugins, yes, use `wget` or `curl`. There's no discovery mechanism or standard there yet.

**Comment by wyardley** [comment]
> Yep, I believe something like Circle is always going to try to invoke a shell wrapper around anything with run. For plugins, yes, use wget or curl. There's no discovery mechanism or standard there yet.

right, the issue is that there's no `curl` in the container, and wget is the busybox one. That said, I was able to get it to work
```yaml
  tflint:
    docker:
      - image: wata727/tflint:0.20.2
        entrypoint: /bin/sh ## not sure if it's needed, given your comment above
    steps:
      - checkout
      - run:
          name: Setup GCP plugin
          command: |
            cd /tmp
            wget -q https://github.com/terraform-linters/tflint-ruleset-google/releases/download/v0.1.0/tflint-ruleset-google_linux_amd64.zip
            mkdir -p ~/.tflint.d/plugins
            unzip tflint-ruleset-google_linux_amd64.zip
            cp tflint-ruleset-google ~/.tflint.d/plugins/
      - run:
          name: Check Terraform configurations with tflint
          command: |
            RETCODE=0
            for DIR in $(find . -type f -name "*.tf" -exec dirname {} \; | sort -u) ; do echo $DIR ; tflint $DIR || RETCODE=$((RETCODE+$?)) ; done
            if [[ $RETCODE -ge 1 ]]; then exit $RETCODE ; fi
```
